# Generated by Django 3.1.2 on 2020-10-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20, unique=True)),
                ('leave_allowance', models.IntegerField(default=0)),
                ('annual_leave', models.IntegerField(default=10)),
                ('carer_leave', models.IntegerField(default=10)),
                ('blood_donor_leave', models.IntegerField(default=10)),
                ('sick_certificate_leave', models.IntegerField(default=10)),
                ('sick_leave', models.IntegerField(default=10)),
                ('parental_leave', models.IntegerField(default=10)),
                ('unpaid_leave', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
