# Generated by Django 3.1.2 on 2020-10-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='request_history',
            field=models.TextField(default=''),
        ),
    ]
