# Generated by Django 3.1.2 on 2020-10-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_staff_request_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='request_approve',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='staff',
            name='manager',
            field=models.CharField(default='abhi', max_length=20),
        ),
    ]
